/**
 * @source https://www.six-group.com/en/products-services/financial-information/data-standards.html#scrollTo=maintenance-agency
 */
export const currencyCodes = [
  {
    country: 'AFGHANISTAN',
    name: 'Afghani',
    alpha: 'AFN',
    numeric: 971,
    minor: 2,
  },
  {
    country: 'ÅLAND ISLANDS',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'ALBANIA',
    name: 'Lek',
    alpha: 'ALL',
    numeric: '008',
    minor: 2,
  },
  {
    country: 'ALGERIA',
    name: 'Algerian Dinar',
    alpha: 'DZD',
    numeric: '012',
    minor: 2,
  },
  {
    country: 'AMERICAN SAMOA',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'ANDORRA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'ANGOLA',
    name: 'Kwanza',
    alpha: 'AOA',
    numeric: 973,
    minor: 2,
  },
  {
    country: 'ANGUILLA',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'ANTARCTICA',
    name: 'No universal currency',
    alpha: '',
    numeric: '',
    minor: '',
  },
  {
    country: 'ANTIGUA AND BARBUDA',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'ARGENTINA',
    name: 'Argentine Peso',
    alpha: 'ARS',
    numeric: '032',
    minor: 2,
  },
  {
    country: 'ARMENIA',
    name: 'Armenian Dram',
    alpha: 'AMD',
    numeric: '051',
    minor: 2,
  },
  {
    country: 'ARUBA',
    name: 'Aruban Florin',
    alpha: 'AWG',
    numeric: 533,
    minor: 2,
  },
  {
    country: 'AUSTRALIA',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'AUSTRIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'AZERBAIJAN',
    name: 'Azerbaijan Manat',
    alpha: 'AZN',
    numeric: 944,
    minor: 2,
  },
  {
    country: 'BAHAMAS (THE)',
    name: 'Bahamian Dollar',
    alpha: 'BSD',
    numeric: '044',
    minor: 2,
  },
  {
    country: 'BAHRAIN',
    name: 'Bahraini Dinar',
    alpha: 'BHD',
    numeric: '048',
    minor: 3,
  },
  {
    country: 'BANGLADESH',
    name: 'Taka',
    alpha: 'BDT',
    numeric: '050',
    minor: 2,
  },
  {
    country: 'BARBADOS',
    name: 'Barbados Dollar',
    alpha: 'BBD',
    numeric: '052',
    minor: 2,
  },
  {
    country: 'BELARUS',
    name: 'Belarusian Ruble',
    alpha: 'BYN',
    numeric: 933,
    minor: 2,
  },
  {
    country: 'BELGIUM',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'BELIZE',
    name: 'Belize Dollar',
    alpha: 'BZD',
    numeric: '084',
    minor: 2,
  },
  {
    country: 'BENIN',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'BERMUDA',
    name: 'Bermudian Dollar',
    alpha: 'BMD',
    numeric: '060',
    minor: 2,
  },
  {
    country: 'BHUTAN',
    name: 'Indian Rupee',
    alpha: 'INR',
    numeric: 356,
    minor: 2,
  },
  {
    country: 'BHUTAN',
    name: 'Ngultrum',
    alpha: 'BTN',
    numeric: '064',
    minor: 2,
  },
  {
    country: 'BOLIVIA (PLURINATIONAL STATE OF)',
    name: 'Boliviano',
    alpha: 'BOB',
    numeric: '068',
    minor: 2,
  },
  {
    country: 'BOLIVIA (PLURINATIONAL STATE OF)',
    name: 'Mvdol',
    alpha: 'BOV',
    numeric: 984,
    minor: 2,
  },
  {
    country: 'BONAIRE, SINT EUSTATIUS AND SABA',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'BOSNIA AND HERZEGOVINA',
    name: 'Convertible Mark',
    alpha: 'BAM',
    numeric: 977,
    minor: 2,
  },
  {
    country: 'BOTSWANA',
    name: 'Pula',
    alpha: 'BWP',
    numeric: '072',
    minor: 2,
  },
  {
    country: 'BOUVET ISLAND',
    name: 'Norwegian Krone',
    alpha: 'NOK',
    numeric: 578,
    minor: 2,
  },
  {
    country: 'BRAZIL',
    name: 'Brazilian Real',
    alpha: 'BRL',
    numeric: 986,
    minor: 2,
  },
  {
    country: 'BRITISH INDIAN OCEAN TERRITORY (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'BRUNEI DARUSSALAM',
    name: 'Brunei Dollar',
    alpha: 'BND',
    numeric: '096',
    minor: 2,
  },
  {
    country: 'BULGARIA',
    name: 'Bulgarian Lev',
    alpha: 'BGN',
    numeric: 975,
    minor: 2,
  },
  {
    country: 'BURKINA FASO',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'BURUNDI',
    name: 'Burundi Franc',
    alpha: 'BIF',
    numeric: 108,
    minor: 0,
  },
  {
    country: 'CABO VERDE',
    name: 'Cabo Verde Escudo',
    alpha: 'CVE',
    numeric: 132,
    minor: 2,
  },
  {
    country: 'CAMBODIA',
    name: 'Riel',
    alpha: 'KHR',
    numeric: 116,
    minor: 2,
  },
  {
    country: 'CAMEROON',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'CANADA',
    name: 'Canadian Dollar',
    alpha: 'CAD',
    numeric: 124,
    minor: 2,
  },
  {
    country: 'CAYMAN ISLANDS (THE)',
    name: 'Cayman Islands Dollar',
    alpha: 'KYD',
    numeric: 136,
    minor: 2,
  },
  {
    country: 'CENTRAL AFRICAN REPUBLIC (THE)',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'CHAD',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'CHILE',
    name: 'Chilean Peso',
    alpha: 'CLP',
    numeric: 152,
    minor: 0,
  },
  {
    country: 'CHILE',
    name: 'Unidad de Fomento',
    alpha: 'CLF',
    numeric: 990,
    minor: 4,
  },
  {
    country: 'CHINA',
    name: 'Yuan Renminbi',
    alpha: 'CNY',
    numeric: 156,
    minor: 2,
  },
  {
    country: 'CHRISTMAS ISLAND',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'COCOS (KEELING) ISLANDS (THE)',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'COLOMBIA',
    name: 'Colombian Peso',
    alpha: 'COP',
    numeric: 170,
    minor: 2,
  },
  {
    country: 'COLOMBIA',
    name: 'Unidad de Valor Real',
    alpha: 'COU',
    numeric: 970,
    minor: 2,
  },
  {
    country: 'COMOROS (THE)',
    name: 'Comorian Franc',
    alpha: 'KMF',
    numeric: 174,
    minor: 0,
  },
  {
    country: 'CONGO (THE DEMOCRATIC REPUBLIC OF THE)',
    name: 'Congolese Franc',
    alpha: 'CDF',
    numeric: 976,
    minor: 2,
  },
  {
    country: 'CONGO (THE)',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'COOK ISLANDS (THE)',
    name: 'New Zealand Dollar',
    alpha: 'NZD',
    numeric: 554,
    minor: 2,
  },
  {
    country: 'COSTA RICA',
    name: 'Costa Rican Colon',
    alpha: 'CRC',
    numeric: 188,
    minor: 2,
  },
  {
    country: "CÔTE D'IVOIRE",
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'CROATIA',
    name: 'Kuna',
    alpha: 'HRK',
    numeric: 191,
    minor: 2,
  },
  {
    country: 'CUBA',
    name: 'Cuban Peso',
    alpha: 'CUP',
    numeric: 192,
    minor: 2,
  },
  {
    country: 'CUBA',
    name: 'Peso Convertible',
    alpha: 'CUC',
    numeric: 931,
    minor: 2,
  },
  {
    country: 'CURAÇAO',
    name: 'Netherlands Antillean Guilder',
    alpha: 'ANG',
    numeric: 532,
    minor: 2,
  },
  {
    country: 'CYPRUS',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'CZECHIA',
    name: 'Czech Koruna',
    alpha: 'CZK',
    numeric: 203,
    minor: 2,
  },
  {
    country: 'DENMARK',
    name: 'Danish Krone',
    alpha: 'DKK',
    numeric: 208,
    minor: 2,
  },
  {
    country: 'DJIBOUTI',
    name: 'Djibouti Franc',
    alpha: 'DJF',
    numeric: 262,
    minor: 0,
  },
  {
    country: 'DOMINICA',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'DOMINICAN REPUBLIC (THE)',
    name: 'Dominican Peso',
    alpha: 'DOP',
    numeric: 214,
    minor: 2,
  },
  {
    country: 'ECUADOR',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'EGYPT',
    name: 'Egyptian Pound',
    alpha: 'EGP',
    numeric: 818,
    minor: 2,
  },
  {
    country: 'EL SALVADOR',
    name: 'El Salvador Colon',
    alpha: 'SVC',
    numeric: 222,
    minor: 2,
  },
  {
    country: 'EL SALVADOR',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'EQUATORIAL GUINEA',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'ERITREA',
    name: 'Nakfa',
    alpha: 'ERN',
    numeric: 232,
    minor: 2,
  },
  {
    country: 'ESTONIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'ESWATINI',
    name: 'Lilangeni',
    alpha: 'SZL',
    numeric: 748,
    minor: 2,
  },
  {
    country: 'ETHIOPIA',
    name: 'Ethiopian Birr',
    alpha: 'ETB',
    numeric: 230,
    minor: 2,
  },
  {
    country: 'EUROPEAN UNION',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'FALKLAND ISLANDS (THE) [MALVINAS]',
    name: 'Falkland Islands Pound',
    alpha: 'FKP',
    numeric: 238,
    minor: 2,
  },
  {
    country: 'FAROE ISLANDS (THE)',
    name: 'Danish Krone',
    alpha: 'DKK',
    numeric: 208,
    minor: 2,
  },
  {
    country: 'FIJI',
    name: 'Fiji Dollar',
    alpha: 'FJD',
    numeric: 242,
    minor: 2,
  },
  {
    country: 'FINLAND',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'FRANCE',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'FRENCH GUIANA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'FRENCH POLYNESIA',
    name: 'CFP Franc',
    alpha: 'XPF',
    numeric: 953,
    minor: 0,
  },
  {
    country: 'FRENCH SOUTHERN TERRITORIES (THE)',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'GABON',
    name: 'CFA Franc BEAC',
    alpha: 'XAF',
    numeric: 950,
    minor: 0,
  },
  {
    country: 'GAMBIA (THE)',
    name: 'Dalasi',
    alpha: 'GMD',
    numeric: 270,
    minor: 2,
  },
  {
    country: 'GEORGIA',
    name: 'Lari',
    alpha: 'GEL',
    numeric: 981,
    minor: 2,
  },
  {
    country: 'GERMANY',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'GHANA',
    name: 'Ghana Cedi',
    alpha: 'GHS',
    numeric: 936,
    minor: 2,
  },
  {
    country: 'GIBRALTAR',
    name: 'Gibraltar Pound',
    alpha: 'GIP',
    numeric: 292,
    minor: 2,
  },
  {
    country: 'GREECE',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'GREENLAND',
    name: 'Danish Krone',
    alpha: 'DKK',
    numeric: 208,
    minor: 2,
  },
  {
    country: 'GRENADA',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'GUADELOUPE',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'GUAM',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'GUATEMALA',
    name: 'Quetzal',
    alpha: 'GTQ',
    numeric: 320,
    minor: 2,
  },
  {
    country: 'GUERNSEY',
    name: 'Pound Sterling',
    alpha: 'GBP',
    numeric: 826,
    minor: 2,
  },
  {
    country: 'GUINEA',
    name: 'Guinean Franc',
    alpha: 'GNF',
    numeric: 324,
    minor: 0,
  },
  {
    country: 'GUINEA-BISSAU',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'GUYANA',
    name: 'Guyana Dollar',
    alpha: 'GYD',
    numeric: 328,
    minor: 2,
  },
  {
    country: 'HAITI',
    name: 'Gourde',
    alpha: 'HTG',
    numeric: 332,
    minor: 2,
  },
  {
    country: 'HAITI',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'HEARD ISLAND AND McDONALD ISLANDS',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'HOLY SEE (THE)',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'HONDURAS',
    name: 'Lempira',
    alpha: 'HNL',
    numeric: 340,
    minor: 2,
  },
  {
    country: 'HONG KONG',
    name: 'Hong Kong Dollar',
    alpha: 'HKD',
    numeric: 344,
    minor: 2,
  },
  {
    country: 'HUNGARY',
    name: 'Forint',
    alpha: 'HUF',
    numeric: 348,
    minor: 2,
  },
  {
    country: 'ICELAND',
    name: 'Iceland Krona',
    alpha: 'ISK',
    numeric: 352,
    minor: 0,
  },
  {
    country: 'INDIA',
    name: 'Indian Rupee',
    alpha: 'INR',
    numeric: 356,
    minor: 2,
  },
  {
    country: 'INDONESIA',
    name: 'Rupiah',
    alpha: 'IDR',
    numeric: 360,
    minor: 2,
  },
  {
    country: 'INTERNATIONAL MONETARY FUND (IMF)',
    name: 'SDR (Special Drawing Right)',
    alpha: 'XDR',
    numeric: 960,
    minor: 'N.A.',
  },
  {
    country: 'IRAN (ISLAMIC REPUBLIC OF)',
    name: 'Iranian Rial',
    alpha: 'IRR',
    numeric: 364,
    minor: 2,
  },
  {
    country: 'IRAQ',
    name: 'Iraqi Dinar',
    alpha: 'IQD',
    numeric: 368,
    minor: 3,
  },
  {
    country: 'IRELAND',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'ISLE OF MAN',
    name: 'Pound Sterling',
    alpha: 'GBP',
    numeric: 826,
    minor: 2,
  },
  {
    country: 'ISRAEL',
    name: 'New Israeli Sheqel',
    alpha: 'ILS',
    numeric: 376,
    minor: 2,
  },
  {
    country: 'ITALY',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'JAMAICA',
    name: 'Jamaican Dollar',
    alpha: 'JMD',
    numeric: 388,
    minor: 2,
  },
  {
    country: 'JAPAN',
    name: 'Yen',
    alpha: 'JPY',
    numeric: 392,
    minor: 0,
  },
  {
    country: 'JERSEY',
    name: 'Pound Sterling',
    alpha: 'GBP',
    numeric: 826,
    minor: 2,
  },
  {
    country: 'JORDAN',
    name: 'Jordanian Dinar',
    alpha: 'JOD',
    numeric: 400,
    minor: 3,
  },
  {
    country: 'KAZAKHSTAN',
    name: 'Tenge',
    alpha: 'KZT',
    numeric: 398,
    minor: 2,
  },
  {
    country: 'KENYA',
    name: 'Kenyan Shilling',
    alpha: 'KES',
    numeric: 404,
    minor: 2,
  },
  {
    country: 'KIRIBATI',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)',
    name: 'North Korean Won',
    alpha: 'KPW',
    numeric: 408,
    minor: 2,
  },
  {
    country: 'KOREA (THE REPUBLIC OF)',
    name: 'Won',
    alpha: 'KRW',
    numeric: 410,
    minor: 0,
  },
  {
    country: 'KUWAIT',
    name: 'Kuwaiti Dinar',
    alpha: 'KWD',
    numeric: 414,
    minor: 3,
  },
  {
    country: 'KYRGYZSTAN',
    name: 'Som',
    alpha: 'KGS',
    numeric: 417,
    minor: 2,
  },
  {
    country: 'LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)',
    name: 'Lao Kip',
    alpha: 'LAK',
    numeric: 418,
    minor: 2,
  },
  {
    country: 'LATVIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'LEBANON',
    name: 'Lebanese Pound',
    alpha: 'LBP',
    numeric: 422,
    minor: 2,
  },
  {
    country: 'LESOTHO',
    name: 'Loti',
    alpha: 'LSL',
    numeric: 426,
    minor: 2,
  },
  {
    country: 'LESOTHO',
    name: 'Rand',
    alpha: 'ZAR',
    numeric: 710,
    minor: 2,
  },
  {
    country: 'LIBERIA',
    name: 'Liberian Dollar',
    alpha: 'LRD',
    numeric: 430,
    minor: 2,
  },
  {
    country: 'LIBYA',
    name: 'Libyan Dinar',
    alpha: 'LYD',
    numeric: 434,
    minor: 3,
  },
  {
    country: 'LIECHTENSTEIN',
    name: 'Swiss Franc',
    alpha: 'CHF',
    numeric: 756,
    minor: 2,
  },
  {
    country: 'LITHUANIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'LUXEMBOURG',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MACAO',
    name: 'Pataca',
    alpha: 'MOP',
    numeric: 446,
    minor: 2,
  },
  {
    country: 'NORTH MACEDONIA',
    name: 'Denar',
    alpha: 'MKD',
    numeric: 807,
    minor: 2,
  },
  {
    country: 'MADAGASCAR',
    name: 'Malagasy Ariary',
    alpha: 'MGA',
    numeric: 969,
    minor: 2,
  },
  {
    country: 'MALAWI',
    name: 'Malawi Kwacha',
    alpha: 'MWK',
    numeric: 454,
    minor: 2,
  },
  {
    country: 'MALAYSIA',
    name: 'Malaysian Ringgit',
    alpha: 'MYR',
    numeric: 458,
    minor: 2,
  },
  {
    country: 'MALDIVES',
    name: 'Rufiyaa',
    alpha: 'MVR',
    numeric: 462,
    minor: 2,
  },
  {
    country: 'MALI',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'MALTA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MARSHALL ISLANDS (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'MARTINIQUE',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MAURITANIA',
    name: 'Ouguiya',
    alpha: 'MRU',
    numeric: 929,
    minor: 2,
  },
  {
    country: 'MAURITIUS',
    name: 'Mauritius Rupee',
    alpha: 'MUR',
    numeric: 480,
    minor: 2,
  },
  {
    country: 'MAYOTTE',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
    name: 'ADB Unit of Account',
    alpha: 'XUA',
    numeric: 965,
    minor: 'N.A.',
  },
  {
    country: 'MEXICO',
    name: 'Mexican Peso',
    alpha: 'MXN',
    numeric: 484,
    minor: 2,
  },
  {
    country: 'MEXICO',
    name: 'Mexican Unidad de Inversion (UDI)',
    alpha: 'MXV',
    numeric: 979,
    minor: 2,
  },
  {
    country: 'MICRONESIA (FEDERATED STATES OF)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'MOLDOVA (THE REPUBLIC OF)',
    name: 'Moldovan Leu',
    alpha: 'MDL',
    numeric: 498,
    minor: 2,
  },
  {
    country: 'MONACO',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MONGOLIA',
    name: 'Tugrik',
    alpha: 'MNT',
    numeric: 496,
    minor: 2,
  },
  {
    country: 'MONTENEGRO',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'MONTSERRAT',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'MOROCCO',
    name: 'Moroccan Dirham',
    alpha: 'MAD',
    numeric: 504,
    minor: 2,
  },
  {
    country: 'MOZAMBIQUE',
    name: 'Mozambique Metical',
    alpha: 'MZN',
    numeric: 943,
    minor: 2,
  },
  {
    country: 'MYANMAR',
    name: 'Kyat',
    alpha: 'MMK',
    numeric: 104,
    minor: 2,
  },
  {
    country: 'NAMIBIA',
    name: 'Namibia Dollar',
    alpha: 'NAD',
    numeric: 516,
    minor: 2,
  },
  {
    country: 'NAMIBIA',
    name: 'Rand',
    alpha: 'ZAR',
    numeric: 710,
    minor: 2,
  },
  {
    country: 'NAURU',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'NEPAL',
    name: 'Nepalese Rupee',
    alpha: 'NPR',
    numeric: 524,
    minor: 2,
  },
  {
    country: 'NETHERLANDS (THE)',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'NEW CALEDONIA',
    name: 'CFP Franc',
    alpha: 'XPF',
    numeric: 953,
    minor: 0,
  },
  {
    country: 'NEW ZEALAND',
    name: 'New Zealand Dollar',
    alpha: 'NZD',
    numeric: 554,
    minor: 2,
  },
  {
    country: 'NICARAGUA',
    name: 'Cordoba Oro',
    alpha: 'NIO',
    numeric: 558,
    minor: 2,
  },
  {
    country: 'NIGER (THE)',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'NIGERIA',
    name: 'Naira',
    alpha: 'NGN',
    numeric: 566,
    minor: 2,
  },
  {
    country: 'NIUE',
    name: 'New Zealand Dollar',
    alpha: 'NZD',
    numeric: 554,
    minor: 2,
  },
  {
    country: 'NORFOLK ISLAND',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'NORTHERN MARIANA ISLANDS (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'NORWAY',
    name: 'Norwegian Krone',
    alpha: 'NOK',
    numeric: 578,
    minor: 2,
  },
  {
    country: 'OMAN',
    name: 'Rial Omani',
    alpha: 'OMR',
    numeric: 512,
    minor: 3,
  },
  {
    country: 'PAKISTAN',
    name: 'Pakistan Rupee',
    alpha: 'PKR',
    numeric: 586,
    minor: 2,
  },
  {
    country: 'PALAU',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'PALESTINE, STATE OF',
    name: 'No universal currency',
    alpha: '',
    numeric: '',
    minor: '',
  },
  {
    country: 'PANAMA',
    name: 'Balboa',
    alpha: 'PAB',
    numeric: 590,
    minor: 2,
  },
  {
    country: 'PANAMA',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'PAPUA NEW GUINEA',
    name: 'Kina',
    alpha: 'PGK',
    numeric: 598,
    minor: 2,
  },
  {
    country: 'PARAGUAY',
    name: 'Guarani',
    alpha: 'PYG',
    numeric: 600,
    minor: 0,
  },
  {
    country: 'PERU',
    name: 'Sol',
    alpha: 'PEN',
    numeric: 604,
    minor: 2,
  },
  {
    country: 'PHILIPPINES (THE)',
    name: 'Philippine Peso',
    alpha: 'PHP',
    numeric: 608,
    minor: 2,
  },
  {
    country: 'PITCAIRN',
    name: 'New Zealand Dollar',
    alpha: 'NZD',
    numeric: 554,
    minor: 2,
  },
  {
    country: 'POLAND',
    name: 'Zloty',
    alpha: 'PLN',
    numeric: 985,
    minor: 2,
  },
  {
    country: 'PORTUGAL',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'PUERTO RICO',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'QATAR',
    name: 'Qatari Rial',
    alpha: 'QAR',
    numeric: 634,
    minor: 2,
  },
  {
    country: 'RÉUNION',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'ROMANIA',
    name: 'Romanian Leu',
    alpha: 'RON',
    numeric: 946,
    minor: 2,
  },
  {
    country: 'RUSSIAN FEDERATION (THE)',
    name: 'Russian Ruble',
    alpha: 'RUB',
    numeric: 643,
    minor: 2,
  },
  {
    country: 'RWANDA',
    name: 'Rwanda Franc',
    alpha: 'RWF',
    numeric: 646,
    minor: 0,
  },
  {
    country: 'SAINT BARTHÉLEMY',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
    name: 'Saint Helena Pound',
    alpha: 'SHP',
    numeric: 654,
    minor: 2,
  },
  {
    country: 'SAINT KITTS AND NEVIS',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'SAINT LUCIA',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'SAINT MARTIN (FRENCH PART)',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SAINT PIERRE AND MIQUELON',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SAINT VINCENT AND THE GRENADINES',
    name: 'East Caribbean Dollar',
    alpha: 'XCD',
    numeric: 951,
    minor: 2,
  },
  {
    country: 'SAMOA',
    name: 'Tala',
    alpha: 'WST',
    numeric: 882,
    minor: 2,
  },
  {
    country: 'SAN MARINO',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SAO TOME AND PRINCIPE',
    name: 'Dobra',
    alpha: 'STN',
    numeric: 930,
    minor: 2,
  },
  {
    country: 'SAUDI ARABIA',
    name: 'Saudi Riyal',
    alpha: 'SAR',
    numeric: 682,
    minor: 2,
  },
  {
    country: 'SENEGAL',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'SERBIA',
    name: 'Serbian Dinar',
    alpha: 'RSD',
    numeric: 941,
    minor: 2,
  },
  {
    country: 'SEYCHELLES',
    name: 'Seychelles Rupee',
    alpha: 'SCR',
    numeric: 690,
    minor: 2,
  },
  {
    country: 'SIERRA LEONE',
    name: 'Leone',
    alpha: 'SLL',
    numeric: 694,
    minor: 2,
  },
  {
    country: 'SINGAPORE',
    name: 'Singapore Dollar',
    alpha: 'SGD',
    numeric: 702,
    minor: 2,
  },
  {
    country: 'SINT MAARTEN (DUTCH PART)',
    name: 'Netherlands Antillean Guilder',
    alpha: 'ANG',
    numeric: 532,
    minor: 2,
  },
  {
    country: 'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE',
    name: 'Sucre',
    alpha: 'XSU',
    numeric: 994,
    minor: 'N.A.',
  },
  {
    country: 'SLOVAKIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SLOVENIA',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SOLOMON ISLANDS',
    name: 'Solomon Islands Dollar',
    alpha: 'SBD',
    numeric: '090',
    minor: 2,
  },
  {
    country: 'SOMALIA',
    name: 'Somali Shilling',
    alpha: 'SOS',
    numeric: 706,
    minor: 2,
  },
  {
    country: 'SOUTH AFRICA',
    name: 'Rand',
    alpha: 'ZAR',
    numeric: 710,
    minor: 2,
  },
  {
    country: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
    name: 'No universal currency',
    alpha: '',
    numeric: '',
    minor: '',
  },
  {
    country: 'SOUTH SUDAN',
    name: 'South Sudanese Pound',
    alpha: 'SSP',
    numeric: 728,
    minor: 2,
  },
  {
    country: 'SPAIN',
    name: 'Euro',
    alpha: 'EUR',
    numeric: 978,
    minor: 2,
  },
  {
    country: 'SRI LANKA',
    name: 'Sri Lanka Rupee',
    alpha: 'LKR',
    numeric: 144,
    minor: 2,
  },
  {
    country: 'SUDAN (THE)',
    name: 'Sudanese Pound',
    alpha: 'SDG',
    numeric: 938,
    minor: 2,
  },
  {
    country: 'SURINAME',
    name: 'Surinam Dollar',
    alpha: 'SRD',
    numeric: 968,
    minor: 2,
  },
  {
    country: 'SVALBARD AND JAN MAYEN',
    name: 'Norwegian Krone',
    alpha: 'NOK',
    numeric: 578,
    minor: 2,
  },
  {
    country: 'SWEDEN',
    name: 'Swedish Krona',
    alpha: 'SEK',
    numeric: 752,
    minor: 2,
  },
  {
    country: 'SWITZERLAND',
    name: 'Swiss Franc',
    alpha: 'CHF',
    numeric: 756,
    minor: 2,
  },
  {
    country: 'SWITZERLAND',
    name: 'WIR Euro',
    alpha: 'CHE',
    numeric: 947,
    minor: 2,
  },
  {
    country: 'SWITZERLAND',
    name: 'WIR Franc',
    alpha: 'CHW',
    numeric: 948,
    minor: 2,
  },
  {
    country: 'SYRIAN ARAB REPUBLIC',
    name: 'Syrian Pound',
    alpha: 'SYP',
    numeric: 760,
    minor: 2,
  },
  {
    country: 'TAIWAN (PROVINCE OF CHINA)',
    name: 'New Taiwan Dollar',
    alpha: 'TWD',
    numeric: 901,
    minor: 2,
  },
  {
    country: 'TAJIKISTAN',
    name: 'Somoni',
    alpha: 'TJS',
    numeric: 972,
    minor: 2,
  },
  {
    country: 'TANZANIA, UNITED REPUBLIC OF',
    name: 'Tanzanian Shilling',
    alpha: 'TZS',
    numeric: 834,
    minor: 2,
  },
  {
    country: 'THAILAND',
    name: 'Baht',
    alpha: 'THB',
    numeric: 764,
    minor: 2,
  },
  {
    country: 'TIMOR-LESTE',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'TOGO',
    name: 'CFA Franc BCEAO',
    alpha: 'XOF',
    numeric: 952,
    minor: 0,
  },
  {
    country: 'TOKELAU',
    name: 'New Zealand Dollar',
    alpha: 'NZD',
    numeric: 554,
    minor: 2,
  },
  {
    country: 'TONGA',
    name: 'Pa’anga',
    alpha: 'TOP',
    numeric: 776,
    minor: 2,
  },
  {
    country: 'TRINIDAD AND TOBAGO',
    name: 'Trinidad and Tobago Dollar',
    alpha: 'TTD',
    numeric: 780,
    minor: 2,
  },
  {
    country: 'TUNISIA',
    name: 'Tunisian Dinar',
    alpha: 'TND',
    numeric: 788,
    minor: 3,
  },
  {
    country: 'TURKEY',
    name: 'Turkish Lira',
    alpha: 'TRY',
    numeric: 949,
    minor: 2,
  },
  {
    country: 'TURKMENISTAN',
    name: 'Turkmenistan New Manat',
    alpha: 'TMT',
    numeric: 934,
    minor: 2,
  },
  {
    country: 'TURKS AND CAICOS ISLANDS (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'TUVALU',
    name: 'Australian Dollar',
    alpha: 'AUD',
    numeric: '036',
    minor: 2,
  },
  {
    country: 'UGANDA',
    name: 'Uganda Shilling',
    alpha: 'UGX',
    numeric: 800,
    minor: 0,
  },
  {
    country: 'UKRAINE',
    name: 'Hryvnia',
    alpha: 'UAH',
    numeric: 980,
    minor: 2,
  },
  {
    country: 'UNITED ARAB EMIRATES (THE)',
    name: 'UAE Dirham',
    alpha: 'AED',
    numeric: 784,
    minor: 2,
  },
  {
    country: 'UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)',
    name: 'Pound Sterling',
    alpha: 'GBP',
    numeric: 826,
    minor: 2,
  },
  {
    country: 'UNITED STATES MINOR OUTLYING ISLANDS (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'UNITED STATES OF AMERICA (THE)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'UNITED STATES OF AMERICA (THE)',
    name: 'US Dollar (Next day)',
    alpha: 'USN',
    numeric: 997,
    minor: 2,
  },
  {
    country: 'URUGUAY',
    name: 'Peso Uruguayo',
    alpha: 'UYU',
    numeric: 858,
    minor: 2,
  },
  {
    country: 'URUGUAY',
    name: 'Uruguay Peso en Unidades Indexadas (UI)',
    alpha: 'UYI',
    numeric: 940,
    minor: 0,
  },
  {
    country: 'URUGUAY',
    name: 'Unidad Previsional',
    alpha: 'UYW',
    numeric: 927,
    minor: 4,
  },
  {
    country: 'UZBEKISTAN',
    name: 'Uzbekistan Sum',
    alpha: 'UZS',
    numeric: 860,
    minor: 2,
  },
  {
    country: 'VANUATU',
    name: 'Vatu',
    alpha: 'VUV',
    numeric: 548,
    minor: 0,
  },
  {
    country: 'VENEZUELA (BOLIVARIAN REPUBLIC OF)',
    name: 'Bolívar Soberano',
    alpha: 'VES',
    numeric: 928,
    minor: 2,
  },
  {
    country: 'VIET NAM',
    name: 'Dong',
    alpha: 'VND',
    numeric: 704,
    minor: 0,
  },
  {
    country: 'VIRGIN ISLANDS (BRITISH)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'VIRGIN ISLANDS (U.S.)',
    name: 'US Dollar',
    alpha: 'USD',
    numeric: 840,
    minor: 2,
  },
  {
    country: 'WALLIS AND FUTUNA',
    name: 'CFP Franc',
    alpha: 'XPF',
    numeric: 953,
    minor: 0,
  },
  {
    country: 'WESTERN SAHARA',
    name: 'Moroccan Dirham',
    alpha: 'MAD',
    numeric: 504,
    minor: 2,
  },
  {
    country: 'YEMEN',
    name: 'Yemeni Rial',
    alpha: 'YER',
    numeric: 886,
    minor: 2,
  },
  {
    country: 'ZAMBIA',
    name: 'Zambian Kwacha',
    alpha: 'ZMW',
    numeric: 967,
    minor: 2,
  },
  {
    country: 'ZIMBABWE',
    name: 'Zimbabwe Dollar',
    alpha: 'ZWL',
    numeric: 932,
    minor: 2,
  },
  {
    country: 'ZZ01_Bond Markets Unit European_EURCO',
    name: 'Bond Markets Unit European Composite Unit (EURCO)',
    alpha: 'XBA',
    numeric: 955,
    minor: 'N.A.',
  },
  {
    country: 'ZZ02_Bond Markets Unit European_EMU-6',
    name: 'Bond Markets Unit European Monetary Unit (E.M.U.-6)',
    alpha: 'XBB',
    numeric: 956,
    minor: 'N.A.',
  },
  {
    country: 'ZZ03_Bond Markets Unit European_EUA-9',
    name: 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)',
    alpha: 'XBC',
    numeric: 957,
    minor: 'N.A.',
  },
  {
    country: 'ZZ04_Bond Markets Unit European_EUA-17',
    name: 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)',
    alpha: 'XBD',
    numeric: 958,
    minor: 'N.A.',
  },
  {
    country: 'ZZ06_Testing_Code',
    name: 'Codes specifically reserved for testing purposes',
    alpha: 'XTS',
    numeric: 963,
    minor: 'N.A.',
  },
  {
    country: 'ZZ07_No_Currency',
    name: 'The codes assigned for transactions where no currency is involved',
    alpha: 'XXX',
    numeric: 999,
    minor: 'N.A.',
  },
  {
    country: 'ZZ08_Gold',
    name: 'Gold',
    alpha: 'XAU',
    numeric: 959,
    minor: 'N.A.',
  },
  {
    country: 'ZZ09_Palladium',
    name: 'Palladium',
    alpha: 'XPD',
    numeric: 964,
    minor: 'N.A.',
  },
  {
    country: 'ZZ10_Platinum',
    name: 'Platinum',
    alpha: 'XPT',
    numeric: 962,
    minor: 'N.A.',
  },
  {
    country: 'ZZ11_Silver',
    name: 'Silver',
    alpha: 'XAG',
    numeric: 961,
    minor: 'N.A.',
  },
] as const
