# This workflow will do a clean install of node dependencies, build the source
# code and run tests across different versions of node For more information
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [saga]
  pull_request:
    branches: [saga]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5

    # Cache node_modules between builds based on the yarn.lock file's hash.
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install packages
      run: yarn install

    - name: Build TypeScript
      run: yarn run build
