# This workflow will do a clean install of node dependencies, build the source
# code and run tests.
# For more information
# see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches:
      - saga
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/codesee-arch-diagram.yml'
      - '.github/workflows/frontend-unit-tests.yml'
      - '.github/workflows/frontend-e2e-tests.yml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'frontend/**'
      - '.github/workflows/codesee-arch-diagram.yml'
      - '.github/workflows/frontend-unit-tests.yml'
      - '.github/workflows/frontend-e2e-tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: distributeaid_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node_modules between builds based on the yarn.lock file's hash.
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build TypeScript
        run: yarn run build

      - name: Run tests
        run: yarn run test-ci
