name: Ensure source code is properly formatted

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Cache node_modules between builds based on the yarn.lock file's hash.
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Format source code with prettier
        run: npx prettier --write ./

      - name: Commit changes
        run: |
          if ! git diff --exit-code --name-only; then
            echo "machine github.com login accesskey password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
            git config --global user.email "actions@example.com"
            git config --global user.name "GitHub Actions"
            git add -A
            git commit -m "style: ensure source code is properly formatted"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          fi
