name: Frontend unit tests

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/codesee-arch-diagram.yml'
      - '.github/workflows/frontend-unit-tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run codegen
        run: yarn codegen
      - name: Install frontend modules
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Run unit tests
        working-directory: frontend
        run: yarn test
      - name: Build
        working-directory: frontend
        run: yarn build
      - name: Archive frontend build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-${{ github.sha }}
          path: frontend/build/**/*
