name: Frontend unit tests

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install modules
        run: yarn --frozen-lockfile
      - name: Run codegen
        run: yarn codegen
      - name: Install frontend modules
        working-directory: frontend
        run: yarn --frozen-lockfile
      - name: Run unit tests
        working-directory: frontend
        run: yarn test
